# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.mapper.dart
    - lib/**/*.config.dart

linter:
  # Aturan kustom untuk memperketat standarisasi kode tim/proyek
  rules:
    # --- Kustomisasi Utama ---
    avoid_print: true
    prefer_single_quotes: true
    always_specify_types: false

    # --- Penguatan Kualitas Kode (Clean Code) ---
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    cascade_invocations: true
    directives_ordering: true
    prefer_relative_imports: true # Memastikan import lokal rapi
    require_trailing_commas: true
    